### PR TITLE
Fix Signature Checks

### LINKED ISSUE #65: Ghost `5.87.1` Signature Checks
The signature checks will fail if using `Ghost:5.87.1`, see - 

1. Changelog: https://github.com/TryGhost/Ghost/releases/tag/v5.87.1
2. The PR: https://github.com/TryGhost/Ghost/pull/20500

### PR DESCRIPTION
**Pull request by ItzNotABug**
This PR addresses #65.

---
Note: Ghost doesn't send the full version in the headers (`Content-Version`) but only `major.minor` so I had to add multiple checks.

### CODE REVIEW

File: utils/misc.js [hunk 1]
```diff
@@ -326,12 +326,34 @@ export default class Miscellaneous {
...
+            .update(`${payload}${timeStamp}`)
+            .digest('hex');
+
+        /**
+         * Build signature for versions below `Ghost:5.87.1`.
+         */
+        const expectedOldSignature = crypto
             .createHmac('sha256', ghostConfigs.secret)
             .update(payload)
             .digest('hex');
```
Comment (ItzNotABug) [inline utils/misc.js]: we could create a separate method here.

Comment (ItzNotABug) [reply utils/misc.js]: Done.
